### ISSUE TITLE
IA3 implementation doesn't add parameters for feedforward layers

### ISSUE THREAD

**Issue by SumanthRH** [r-three/t-few#26]
Hi,

I'm trying to implement your method  (IA)<sup>3</sup> for use with HuggingFace's PEFT library and had a question. In the paper,  it is mentioned that the learned vectors in  (IA)<sup>3</sup> are added for all the position-wise feedfoward layers in the transformer, along with the various attention layers. I ran `src/models/lora.py` and used the config parameters in `configs/ia3.json` to check how the new model layers would be. The typical FeedForward module in T5 is a `T5DenseActDense` module that looks as follows:

  

              (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=768, out_features=3072, bias=False)
              (wo): Linear(in_features=3072, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
              )

Since   (IA)<sup>3</sup>  is implemented as an extension of LoRA, the `Linear` layers are supposed to get converted into `LoRALinear` layers.  However, the config in `ia3.json` sets the parameter   `lora_layers`  to be  "k|v|wi_1.*", which does not include the layers in DenseReluDense (These are attributes with names `wi` and `wo`).  I've tried T5-small, T5-base and T5-3b, and for all of these models, learned vectors are not added for the feedforward layers. I was wondering if I'm doing something wrong or if I'm supposed to use a different config file. Or are (IA)<sup>3</sup> parameters added only for certain feedforward layers?

**Comment by dionman** [comment]
how can this json be written for the case of falcon-7b?

**Comment by SumanthRH** [comment]
Hi @dionman, from the way I understand it, the current $(IA)^3$ code is a thing wrapper around a LoRA implementation. The implementation works only for T5 1.1 - like models with a certain feedforward architecture. For a standard transformer architecture like in BERT, GPT-2, the learned vector should get injected differently for the feedforward block vs the attention block (key, value layers). This is what I got from the paper atleast. 


As of this writing, HuggingFace's PEFT has integrated $(IA)^3$. (My PR here: https://github.com/huggingface/peft/pull/578). That should be simple to use for your use case! 

Also, @muqeeth, do check out the current PEFT implementation!

**Comment by dionman** [comment]
Thanks @SumanthRH. Is this also handling the altered loss function and the normalization proposed in the T-Few recipe?

**Comment by SumanthRH** [comment]
No it does not! PEFT only implements $(IA)$^3, not the full TFew recipe!
