### ISSUE TITLE
Does pl_train.py support TPU training?

### ISSUE THREAD

**Issue by kshre** [r-three/t-few#8]
Hello,
I am interested in using T-Few recipe for some experiments with Google Cloud TPUs. I am wondering whether the pl_train.py script supports TPU already? I read in the Acknowledgments section of the paper the authors cite that TPU cloud was utilised, however in this script I can see that gpu is directly supported. Any pointers will be appreciated, particularly I would like to use T0–11b

**Comment by HaokunLiu** [comment]
Unfortunately no. We used TPU to run some other codebase when experimenting with PromptTuning.
